server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: test
    password: pasw0rd
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
topic.output:
  order-request: order.request
  onboard-customer: onboard.customer
test-mode:
    active: true
    period: 5

